# Rubric (cap at 10):
# Maritime chokepoint: +3
# Hydrocarbon reserves/transit: +2
# Active conflict/occupied territory: +2
# Nuclear program (active or latent): +2
# Strategic minerals: +2
# Western Hemisphere presence: +1
# Major US basing/force presence: +1
# Significant Chinese BRI/debt exposure: +1
# Active sanctions regime: +1
# Regional power or proxy hub: +1

COUNTRIES = [
    # --- A ---
    {
        "iso": "AF", "name": "Afghanistan",
        "structural_interest_score": 5,
        "score_rationale": "Active conflict/instability (+2), Taliban sanctions (+1), BRI engagement/Chinese interest (+1), regional proxy hub (+1)",
        "key_structural_interests": ["active conflict", "sanctions", "BRI exposure", "proxy hub"],
        "suppression_baseline": "moderate_coverage",
    },
    {
        "iso": "AL", "name": "Albania",
        "structural_interest_score": 1,
        "score_rationale": "NATO member, Adriatic transit corridor (+1)",
        "key_structural_interests": ["NATO flank"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "DZ", "name": "Algeria",
        "structural_interest_score": 3,
        "score_rationale": "Major hydrocarbon reserves and European gas supplier (+2), regional power in Sahel/Maghreb (+1)",
        "key_structural_interests": ["hydrocarbons", "regional power"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "AD", "name": "Andorra",
        "structural_interest_score": 0,
        "score_rationale": "No structural indicators",
        "key_structural_interests": [],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "AO", "name": "Angola",
        "structural_interest_score": 3,
        "score_rationale": "Major offshore hydrocarbon producer (+2), significant Chinese debt/BRI exposure (+1)",
        "key_structural_interests": ["hydrocarbons", "BRI exposure"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "AG", "name": "Antigua and Barbuda",
        "structural_interest_score": 1,
        "score_rationale": "Western Hemisphere presence (+1)",
        "key_structural_interests": ["Western Hemisphere"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "AR", "name": "Argentina",
        "structural_interest_score": 4,
        "score_rationale": "Western Hemisphere presence (+1), major lithium triangle reserves (+2), regional power (+1)",
        "key_structural_interests": ["strategic minerals", "lithium", "Western Hemisphere", "regional power"],
        "suppression_baseline": "moderate_coverage",
    },
    {
        "iso": "AM", "name": "Armenia",
        "structural_interest_score": 4,
        "score_rationale": "Active conflict/occupied territory — Nagorno-Karabakh displacement and Russian-Turkish-Azerbaijani contest (+2), regional proxy hub (+1), BRI adjacent (+1)",
        "key_structural_interests": ["active conflict", "proxy hub", "Russia-Turkey-Azerbaijan theater"],
        "suppression_baseline": "moderate_coverage",
    },
    {
        "iso": "AU", "name": "Australia",
        "structural_interest_score": 5,
        "score_rationale": "Major strategic minerals producer and processor — rare earths, lithium, uranium (+2), major US basing and AUKUS partner (+1), regional power Indo-Pacific (+1), hydrocarbon exports (+1)",
        "key_structural_interests": ["strategic minerals", "US basing", "AUKUS", "regional power", "hydrocarbons"],
        "suppression_baseline": "high_coverage",
    },
    {
        "iso": "AT", "name": "Austria",
        "structural_interest_score": 0,
        "score_rationale": "No structural indicators; neutral EU member",
        "key_structural_interests": [],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "AZ", "name": "Azerbaijan",
        "structural_interest_score": 4,
        "score_rationale": "Hydrocarbon reserves and BTC/TANAP pipeline transit (+2), post-conflict occupied territory in Karabakh (+1), proxy hub between Russia, Turkey, Iran (+1)",
        "key_structural_interests": ["hydrocarbons", "pipeline transit", "proxy hub"],
        "suppression_baseline": "low_coverage",
    },
    # --- B ---
    {
        "iso": "BS", "name": "Bahamas",
        "structural_interest_score": 1,
        "score_rationale": "Western Hemisphere presence (+1)",
        "key_structural_interests": ["Western Hemisphere"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "BH", "name": "Bahrain",
        "structural_interest_score": 4,
        "score_rationale": "US 5th Fleet HQ, major basing presence (+1), Persian Gulf hydrocarbon transit hub (+2), Shia/Sunni proxy dynamic, Iranian pressure (+1)",
        "key_structural_interests": ["US basing", "5th Fleet", "hydrocarbons", "proxy hub"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "BD", "name": "Bangladesh",
        "structural_interest_score": 2,
        "score_rationale": "Significant Chinese BRI/port exposure at Chittagong (+1), Bay of Bengal strategic position (+1)",
        "key_structural_interests": ["BRI exposure", "Bay of Bengal"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "BB", "name": "Barbados",
        "structural_interest_score": 1,
        "score_rationale": "Western Hemisphere presence (+1)",
        "key_structural_interests": ["Western Hemisphere"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "BY", "name": "Belarus",
        "structural_interest_score": 5,
        "score_rationale": "Occupied/co-belligerent in Ukraine war, Russian forward position (+2), active sanctions regime (+1), Russia proxy hub (+1), nuclear weapons hosted (+1 latent nuclear)",
        "key_structural_interests": ["active conflict", "sanctions", "proxy hub", "nuclear hosting", "Russian forward base"],
        "suppression_baseline": "moderate_coverage",
    },
    {
        "iso": "BE", "name": "Belgium",
        "structural_interest_score": 2,
        "score_rationale": "NATO HQ and EU political center (+1), US tactical nuclear weapons hosted (+1)",
        "key_structural_interests": ["NATO HQ", "nuclear hosting"],
        "suppression_baseline": "moderate_coverage",
    },
    {
        "iso": "BZ", "name": "Belize",
        "structural_interest_score": 1,
        "score_rationale": "Western Hemisphere presence (+1)",
        "key_structural_interests": ["Western Hemisphere"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "BJ", "name": "Benin",
        "structural_interest_score": 1,
        "score_rationale": "Sahel jihadist spillover pressure, nascent instability (+1)",
        "key_structural_interests": ["Sahel spillover"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "BT", "name": "Bhutan",
        "structural_interest_score": 1,
        "score_rationale": "Border dispute with China, Himalayan buffer state (+1)",
        "key_structural_interests": ["China border dispute"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "BO", "name": "Bolivia",
        "structural_interest_score": 4,
        "score_rationale": "World's largest lithium reserves (+2), Western Hemisphere presence (+1), BRI/Chinese mineral investment (+1)",
        "key_structural_interests": ["strategic minerals", "lithium", "Western Hemisphere", "BRI exposure"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "BA", "name": "Bosnia and Herzegovina",
        "structural_interest_score": 2,
        "score_rationale": "Occupied/contested political structure, Republika Srpska separatism (+1), Russia-West proxy contest (+1)",
        "key_structural_interests": ["contested territory", "proxy hub"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "BW", "name": "Botswana",
        "structural_interest_score": 2,
        "score_rationale": "Major diamond processing and strategic mineral deposits (+2)",
        "key_structural_interests": ["strategic minerals", "diamonds"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "BR", "name": "Brazil",
        "structural_interest_score": 5,
        "score_rationale": "Western Hemisphere presence (+1), major pre-salt hydrocarbon reserves (+2), regional power (+1), strategic minerals including niobium (+1)",
        "key_structural_interests": ["hydrocarbons", "regional power", "strategic minerals", "Western Hemisphere"],
        "suppression_baseline": "moderate_coverage",
    },
    {
        "iso": "BN", "name": "Brunei",
        "structural_interest_score": 3,
        "score_rationale": "Hydrocarbon reserves (+2), South China Sea territorial dispute (+1)",
        "key_structural_interests": ["hydrocarbons", "South China Sea"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "BG", "name": "Bulgaria",
        "structural_interest_score": 1,
        "score_rationale": "NATO Black Sea flank, Russian gas transit history (+1)",
        "key_structural_interests": ["NATO flank"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "BF", "name": "Burkina Faso",
        "structural_interest_score": 5,
        "score_rationale": "Active jihadist conflict (+2), gold and strategic mineral deposits (+2), Russia/Wagner proxy presence, French expulsion (+1)",
        "key_structural_interests": ["active conflict", "strategic minerals", "gold", "proxy hub", "Wagner"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "BI", "name": "Burundi",
        "structural_interest_score": 2,
        "score_rationale": "Active internal conflict and regional instability (+2)",
        "key_structural_interests": ["active conflict"],
        "suppression_baseline": "suppressed",
    },
    # --- C ---
    {
        "iso": "CV", "name": "Cabo Verde",
        "structural_interest_score": 0,
        "score_rationale": "No structural indicators",
        "key_structural_interests": [],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "KH", "name": "Cambodia",
        "structural_interest_score": 2,
        "score_rationale": "Chinese BRI exposure and Ream Naval Base — PLA access corridor (+1), South China Sea adjacent (+1)",
        "key_structural_interests": ["BRI exposure", "Chinese naval access"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "CM", "name": "Cameroon",
        "structural_interest_score": 4,
        "score_rationale": "Active Anglophone separatist conflict and Boko Haram pressure (+2), hydrocarbon production (+2)",
        "key_structural_interests": ["active conflict", "hydrocarbons"],
        "suppression_baseline": "suppressed",
    },
    {
        "iso": "CA", "name": "Canada",
        "structural_interest_score": 5,
        "score_rationale": "Western Hemisphere presence (+1), major hydrocarbon producer (+2), strategic minerals including uranium and rare earths (+2)",
        "key_structural_interests": ["hydrocarbons", "strategic minerals", "Western Hemisphere"],
        "suppression_baseline": "high_coverage",
    },
    {
        "iso": "CF", "name": "Central African Republic",
        "structural_interest_score": 5,
        "score_rationale": "Active conflict (+2), uranium and strategic mineral deposits (+2), Russia/Wagner proxy hub (+1)",
        "key_structural_interests": ["active conflict", "strategic minerals", "uranium", "proxy hub", "Wagner"],
        "suppression_baseline": "suppressed",
    },
    {
        "iso": "TD", "name": "Chad",
        "structural_interest_score": 5,
        "score_rationale": "Active Sahel conflict and regional instability (+2), hydrocarbon reserves (+2), key Sahel proxy hub — France/US/Russia contest (+1)",
        "key_structural_interests": ["active conflict", "hydrocarbons", "proxy hub", "Sahel"],
        "suppression_baseline": "suppressed",
    },
    {
        "iso": "CL", "name": "Chile",
        "structural_interest_score": 3,
        "score_rationale": "Western Hemisphere presence (+1), major lithium and copper reserves (+2)",
        "key_structural_interests": ["strategic minerals", "lithium", "copper", "Western Hemisphere"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "CO", "name": "Colombia",
        "structural_interest_score": 6,
        "score_rationale": "Western Hemisphere presence (+1), active ELN/FARC-dissident conflict (+2), hydrocarbon reserves (+2), major US basing and regional security partner (+1)",
        "key_structural_interests": ["active conflict", "hydrocarbons", "US basing", "Western Hemisphere"],
        "suppression_baseline": "moderate_coverage",
    },
    {
        "iso": "KM", "name": "Comoros",
        "structural_interest_score": 0,
        "score_rationale": "No structural indicators",
        "key_structural_interests": [],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "CG", "name": "Congo (Republic)",
        "structural_interest_score": 3,
        "score_rationale": "Hydrocarbon production (+2), Chinese BRI/debt exposure (+1)",
        "key_structural_interests": ["hydrocarbons", "BRI exposure"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "CD", "name": "Congo (Democratic Republic)",
        "structural_interest_score": 6,
        "score_rationale": "Active multi-faction conflict (+2), world's largest cobalt reserves plus coltan and strategic minerals (+2), Chinese mining dominance/BRI (+1), regional proxy hub M23/Rwanda/Uganda (+1)",
        "key_structural_interests": ["active conflict", "strategic minerals", "cobalt", "coltan", "BRI exposure", "proxy hub"],
        "suppression_baseline": "suppressed",
    },
    {
        "iso": "CR", "name": "Costa Rica",
        "structural_interest_score": 1,
        "score_rationale": "Western Hemisphere presence (+1)",
        "key_structural_interests": ["Western Hemisphere"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "CI", "name": "Côte d'Ivoire",
        "structural_interest_score": 2,
        "score_rationale": "West African regional economic hub (+1), Sahel instability spillover risk (+1)",
        "key_structural_interests": ["regional hub", "Sahel spillover"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "HR", "name": "Croatia",
        "structural_interest_score": 1,
        "score_rationale": "NATO Adriatic flank, Balkans stability corridor (+1)",
        "key_structural_interests": ["NATO flank"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "CU", "name": "Cuba",
        "structural_interest_score": 4,
        "score_rationale": "Western Hemisphere presence (+1), active US sanctions regime (+1), Russian/Chinese intelligence infrastructure (+1), regional proxy hub (+1)",
        "key_structural_interests": ["sanctions", "proxy hub", "Western Hemisphere", "Russian/Chinese presence"],
        "suppression_baseline": "moderate_coverage",
    },
    {
        "iso": "CY", "name": "Cyprus",
        "structural_interest_score": 4,
        "score_rationale": "Active occupation — Turkish-occupied northern Cyprus (+2), UK sovereign bases (Akrotiri/Dhekelia) with US access (+1), Eastern Med gas fields (+1)",
        "key_structural_interests": ["occupied territory", "US/UK basing", "hydrocarbons"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "CZ", "name": "Czechia",
        "structural_interest_score": 0,
        "score_rationale": "No structural indicators; NATO/EU member",
        "key_structural_interests": [],
        "suppression_baseline": "low_coverage",
    },
    # --- D ---
    {
        "iso": "DK", "name": "Denmark",
        "structural_interest_score": 6,
        "score_rationale": "Controls Danish Straits — only Baltic Sea exit, chokepoint (+3), Greenland: rare earth and strategic mineral deposits (+2), Arctic sovereignty and NATO position (+1)",
        "key_structural_interests": ["maritime chokepoint", "Danish Straits", "strategic minerals", "Greenland", "Arctic"],
        "suppression_baseline": "moderate_coverage",
    },
    {
        "iso": "DJ", "name": "Djibouti",
        "structural_interest_score": 7,
        "score_rationale": "Bab-el-Mandeb chokepoint — Red Sea/Indian Ocean (+3), US Camp Lemonnier basing (+1), Chinese PLA overseas base (+1), BRI exposure (+1), multi-nation basing hub (+1)",
        "key_structural_interests": ["maritime chokepoint", "Bab-el-Mandeb", "US basing", "Chinese base", "BRI exposure", "proxy hub"],
        "suppression_baseline": "suppressed",
    },
    {
        "iso": "DM", "name": "Dominica",
        "structural_interest_score": 1,
        "score_rationale": "Western Hemisphere presence (+1)",
        "key_structural_interests": ["Western Hemisphere"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "DO", "name": "Dominican Republic",
        "structural_interest_score": 1,
        "score_rationale": "Western Hemisphere presence (+1)",
        "key_structural_interests": ["Western Hemisphere"],
        "suppression_baseline": "low_coverage",
    },
    # --- E ---
    {
        "iso": "EC", "name": "Ecuador",
        "structural_interest_score": 3,
        "score_rationale": "Western Hemisphere presence (+1), hydrocarbon producer — Amazon basin oil (+2)",
        "key_structural_interests": ["hydrocarbons", "Western Hemisphere"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "EG", "name": "Egypt",
        "structural_interest_score": 7,
        "score_rationale": "Controls Suez Canal — global maritime chokepoint (+3), major US basing and security partner (+1), regional power (+1), hydrocarbon producer and gas hub (+2)",
        "key_structural_interests": ["maritime chokepoint", "Suez Canal", "US basing", "regional power", "hydrocarbons"],
        "suppression_baseline": "moderate_coverage",
    },
    {
        "iso": "SV", "name": "El Salvador",
        "structural_interest_score": 1,
        "score_rationale": "Western Hemisphere presence (+1)",
        "key_structural_interests": ["Western Hemisphere"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "GQ", "name": "Equatorial Guinea",
        "structural_interest_score": 2,
        "score_rationale": "Significant offshore hydrocarbon production (+2)",
        "key_structural_interests": ["hydrocarbons"],
        "suppression_baseline": "suppressed",
    },
    {
        "iso": "ER", "name": "Eritrea",
        "structural_interest_score": 4,
        "score_rationale": "Active conflict — direct military involvement in Tigray war (+2), Red Sea strategic coastline (+1), proxy hub for regional power contest (+1)",
        "key_structural_interests": ["active conflict", "Red Sea", "proxy hub"],
        "suppression_baseline": "suppressed",
    },
    {
        "iso": "EE", "name": "Estonia",
        "structural_interest_score": 2,
        "score_rationale": "NATO eastern flank, direct Russian border (+1), Baltic Sea access (+1)",
        "key_structural_interests": ["NATO flank", "Russian border"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "SZ", "name": "Eswatini",
        "structural_interest_score": 0,
        "score_rationale": "No structural indicators",
        "key_structural_interests": [],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "ET", "name": "Ethiopia",
        "structural_interest_score": 4,
        "score_rationale": "Active conflict — Tigray war and ongoing ethnic insurgencies (+2), regional power in Horn of Africa (+1), Nile water rights dispute with Egypt (+1)",
        "key_structural_interests": ["active conflict", "regional power", "Nile dispute"],
        "suppression_baseline": "low_coverage",
    },
    # --- F ---
    {
        "iso": "FJ", "name": "Fiji",
        "structural_interest_score": 1,
        "score_rationale": "Chinese BRI/port exposure, Pacific strategic contest (+1)",
        "key_structural_interests": ["BRI exposure"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "FI", "name": "Finland",
        "structural_interest_score": 2,
        "score_rationale": "NATO new member with direct Russian border (+1), Baltic Sea strategic position (+1)",
        "key_structural_interests": ["NATO flank", "Russian border"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "FR", "name": "France",
        "structural_interest_score": 5,
        "score_rationale": "Active nuclear weapons program (+2), regional power and global military presence (+1), major US-allied basing network including Africa and Pacific (+1), strategic minerals via overseas territories (+1)",
        "key_structural_interests": ["nuclear program", "regional power", "global basing", "strategic minerals"],
        "suppression_baseline": "high_coverage",
    },
    # --- G ---
    {
        "iso": "GA", "name": "Gabon",
        "structural_interest_score": 2,
        "score_rationale": "Hydrocarbon production — offshore oil (+2)",
        "key_structural_interests": ["hydrocarbons"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "GM", "name": "Gambia",
        "structural_interest_score": 0,
        "score_rationale": "No structural indicators",
        "key_structural_interests": [],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "GE", "name": "Georgia",
        "structural_interest_score": 5,
        "score_rationale": "Occupied territory — South Ossetia and Abkhazia under Russian control (+2), BTC/SCP pipeline transit corridor (+2), Russia-West proxy contest (+1)",
        "key_structural_interests": ["occupied territory", "pipeline transit", "proxy hub"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "DE", "name": "Germany",
        "structural_interest_score": 4,
        "score_rationale": "Major US basing — EUCOM, Ramstein, Landstuhl (+1), US tactical nuclear weapons hosted (+2 latent nuclear), regional power and NATO anchor (+1)",
        "key_structural_interests": ["US basing", "nuclear hosting", "regional power"],
        "suppression_baseline": "high_coverage",
    },
    {
        "iso": "GH", "name": "Ghana",
        "structural_interest_score": 3,
        "score_rationale": "Strategic minerals — world-class gold deposits (+2), offshore hydrocarbon production (+1)",
        "key_structural_interests": ["strategic minerals", "gold", "hydrocarbons"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "GR", "name": "Greece",
        "structural_interest_score": 3,
        "score_rationale": "Major US basing — Souda Bay, Alexandroupolis (+1), controls Aegean Sea access — strategic maritime corridor (+1), NATO southeastern flank and Eastern Med gas contest (+1)",
        "key_structural_interests": ["US basing", "maritime corridor", "NATO flank"],
        "suppression_baseline": "moderate_coverage",
    },
    {
        "iso": "GD", "name": "Grenada",
        "structural_interest_score": 1,
        "score_rationale": "Western Hemisphere presence (+1)",
        "key_structural_interests": ["Western Hemisphere"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "GT", "name": "Guatemala",
        "structural_interest_score": 1,
        "score_rationale": "Western Hemisphere presence (+1)",
        "key_structural_interests": ["Western Hemisphere"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "GN", "name": "Guinea",
        "structural_interest_score": 3,
        "score_rationale": "World's largest bauxite reserves plus iron ore — critical minerals (+2), Chinese mining dominance/BRI (+1)",
        "key_structural_interests": ["strategic minerals", "bauxite", "BRI exposure"],
        "suppression_baseline": "suppressed",
    },
    {
        "iso": "GW", "name": "Guinea-Bissau",
        "structural_interest_score": 1,
        "score_rationale": "Atlantic narco-trafficking transit hub — structural instability indicator (+1)",
        "key_structural_interests": ["drug transit"],
        "suppression_baseline": "suppressed",
    },
    {
        "iso": "GY", "name": "Guyana",
        "structural_interest_score": 3,
        "score_rationale": "Western Hemisphere presence (+1), massive new deepwater hydrocarbon discoveries — one of world's fastest-growing producers (+2)",
        "key_structural_interests": ["hydrocarbons", "Western Hemisphere"],
        "suppression_baseline": "low_coverage",
    },
    # --- H ---
    {
        "iso": "HT", "name": "Haiti",
        "structural_interest_score": 3,
        "score_rationale": "Western Hemisphere presence (+1), active conflict — state collapse, gang warfare (+2)",
        "key_structural_interests": ["active conflict", "Western Hemisphere"],
        "suppression_baseline": "moderate_coverage",
    },
    {
        "iso": "HN", "name": "Honduras",
        "structural_interest_score": 2,
        "score_rationale": "Western Hemisphere presence (+1), US Soto Cano Air Base — regional military hub (+1)",
        "key_structural_interests": ["Western Hemisphere", "US basing"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "HU", "name": "Hungary",
        "structural_interest_score": 2,
        "score_rationale": "Chinese BRI investment hub, Budapest-Belgrade rail (+1), NATO member acting as Russian gas conduit and political spoiler (+1)",
        "key_structural_interests": ["BRI exposure", "proxy hub"],
        "suppression_baseline": "moderate_coverage",
    },
    # --- I ---
    {
        "iso": "IS", "name": "Iceland",
        "structural_interest_score": 4,
        "score_rationale": "GIUK Gap — North Atlantic chokepoint between Greenland, Iceland, UK (+3), US Keflavik basing access (+1)",
        "key_structural_interests": ["maritime chokepoint", "GIUK Gap", "US basing"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "IN", "name": "India",
        "structural_interest_score": 7,
        "score_rationale": "Nuclear weapons program (+2), regional power (+1), strategic minerals including rare earths (+2), Indian Ocean chokepoint adjacency — controls Andaman sea lanes (+1), major US security partner and arms customer (+1)",
        "key_structural_interests": ["nuclear program", "regional power", "strategic minerals", "Indian Ocean", "US partner"],
        "suppression_baseline": "high_coverage",
    },
    {
        "iso": "ID", "name": "Indonesia",
        "structural_interest_score": 7,
        "score_rationale": "Controls Malacca, Lombok, and Sunda Straits — critical global chokepoints (+3), major hydrocarbon producer (+2), regional power (+1), significant BRI/Chinese investment (+1)",
        "key_structural_interests": ["maritime chokepoint", "Malacca Strait", "hydrocarbons", "regional power", "BRI exposure"],
        "suppression_baseline": "moderate_coverage",
    },
    {
        "iso": "IR", "name": "Iran",
        "structural_interest_score": 9,
        "score_rationale": "Controls northern shore of Strait of Hormuz — world's most critical oil chokepoint (+3), active nuclear program (+2), massive hydrocarbon reserves (+2), active sanctions regime (+1), regional proxy hub — Hezbollah, Houthis, Iraq militias (+1)",
        "key_structural_interests": ["maritime chokepoint", "Strait of Hormuz", "nuclear program", "hydrocarbons", "sanctions", "proxy hub"],
        "suppression_baseline": "high_coverage",
    },
    {
        "iso": "IQ", "name": "Iraq",
        "structural_interest_score": 7,
        "score_rationale": "Massive hydrocarbon reserves — top-5 global producer (+2), active conflict — militia warfare and ISIS remnants (+2), Iran-US proxy contest (+1), major US basing presence (+1), active sanctions history and ongoing restrictions (+1)",
        "key_structural_interests": ["hydrocarbons", "active conflict", "proxy hub", "US basing", "sanctions"],
        "suppression_baseline": "high_coverage",
    },
    {
        "iso": "IE", "name": "Ireland",
        "structural_interest_score": 0,
        "score_rationale": "No structural indicators; neutral EU member",
        "key_structural_interests": [],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "IL", "name": "Israel",
        "structural_interest_score": 7,
        "score_rationale": "Undeclared nuclear weapons program (+2), active conflict — Gaza war, Lebanon, regional escalation (+2), major US security guarantor and basing access (+1), regional power (+1), active sanctions against counterparties (+1)",
        "key_structural_interests": ["nuclear program", "active conflict", "US basing", "regional power", "sanctions"],
        "suppression_baseline": "high_coverage",
    },
    {
        "iso": "IT", "name": "Italy",
        "structural_interest_score": 3,
        "score_rationale": "Major US basing — Sigonella, Aviano, Naples 6th Fleet (+1), US tactical nuclear weapons hosted (+2 latent nuclear), Mediterranean transit hub",
        "key_structural_interests": ["US basing", "nuclear hosting", "Mediterranean hub"],
        "suppression_baseline": "high_coverage",
    },
    # --- J ---
    {
        "iso": "JM", "name": "Jamaica",
        "structural_interest_score": 1,
        "score_rationale": "Western Hemisphere presence (+1)",
        "key_structural_interests": ["Western Hemisphere"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "JP", "name": "Japan",
        "structural_interest_score": 6,
        "score_rationale": "Latent nuclear program — plutonium stockpile, can weaponize rapidly (+2), regional power (+1), strategic minerals processing hub (+2), major US basing — Yokosuka, Kadena, Okinawa (+1)",
        "key_structural_interests": ["nuclear program", "regional power", "strategic minerals", "US basing"],
        "suppression_baseline": "high_coverage",
    },
    {
        "iso": "JO", "name": "Jordan",
        "structural_interest_score": 3,
        "score_rationale": "Major US basing and regional security partner (+1), key stability anchor and proxy buffer — Palestinian/Syrian/Iraqi spillover (+1), US air operations hub against ISIS (+1)",
        "key_structural_interests": ["US basing", "proxy hub", "regional stability"],
        "suppression_baseline": "moderate_coverage",
    },
    # --- K ---
    {
        "iso": "KZ", "name": "Kazakhstan",
        "structural_interest_score": 5,
        "score_rationale": "Major hydrocarbon reserves — Tengiz, Kashagan (+2), world's largest uranium producer (+2), BRI land corridor (+1)",
        "key_structural_interests": ["hydrocarbons", "strategic minerals", "uranium", "BRI exposure"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "KE", "name": "Kenya",
        "structural_interest_score": 2,
        "score_rationale": "Regional power and US counterterrorism hub in East Africa (+1), US basing access (+1)",
        "key_structural_interests": ["regional power", "US basing"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "KI", "name": "Kiribati",
        "structural_interest_score": 1,
        "score_rationale": "Switched diplomatic recognition to China — Pacific strategic contest (+1)",
        "key_structural_interests": ["BRI exposure"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "XK", "name": "Kosovo",
        "structural_interest_score": 2,
        "score_rationale": "Contested sovereignty — ongoing Serbia/Russia pressure (+1), major US basing at Camp Bondsteel (+1)",
        "key_structural_interests": ["contested territory", "US basing"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "KW", "name": "Kuwait",
        "structural_interest_score": 3,
        "score_rationale": "Major hydrocarbon reserves (+2), US basing and pre-positioned equipment (+1)",
        "key_structural_interests": ["hydrocarbons", "US basing"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "KG", "name": "Kyrgyzstan",
        "structural_interest_score": 1,
        "score_rationale": "BRI/Chinese debt exposure (+1)",
        "key_structural_interests": ["BRI exposure"],
        "suppression_baseline": "low_coverage",
    },
    # --- L ---
    {
        "iso": "LA", "name": "Laos",
        "structural_interest_score": 2,
        "score_rationale": "Heavy Chinese BRI debt — Laos-China railway, near-client state (+1), Mekong River strategic corridor (+1)",
        "key_structural_interests": ["BRI exposure", "Mekong corridor"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "LV", "name": "Latvia",
        "structural_interest_score": 2,
        "score_rationale": "NATO eastern flank, direct Russian border (+1), Baltic Sea access and Suwalki corridor adjacent (+1)",
        "key_structural_interests": ["NATO flank", "Russian border"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "LB", "name": "Lebanon",
        "structural_interest_score": 4,
        "score_rationale": "Active conflict — Israeli strikes, Hezbollah war, state collapse (+2), Iran proxy hub — Hezbollah HQ (+1), active sanctions on Hezbollah networks (+1)",
        "key_structural_interests": ["active conflict", "proxy hub", "sanctions"],
        "suppression_baseline": "moderate_coverage",
    },
    {
        "iso": "LS", "name": "Lesotho",
        "structural_interest_score": 0,
        "score_rationale": "No structural indicators",
        "key_structural_interests": [],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "LR", "name": "Liberia",
        "structural_interest_score": 1,
        "score_rationale": "World's second-largest flag of convenience registry — maritime tracking indicator (+1)",
        "key_structural_interests": ["maritime registry"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "LY", "name": "Libya",
        "structural_interest_score": 5,
        "score_rationale": "Active civil conflict — GNA/LNA split (+2), major hydrocarbon reserves (+2), proxy hub — Turkey, Russia, UAE, Egypt contest (+1)",
        "key_structural_interests": ["active conflict", "hydrocarbons", "proxy hub"],
        "suppression_baseline": "moderate_coverage",
    },
    {
        "iso": "LI", "name": "Liechtenstein",
        "structural_interest_score": 0,
        "score_rationale": "No structural indicators",
        "key_structural_interests": [],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "LT", "name": "Lithuania",
        "structural_interest_score": 2,
        "score_rationale": "NATO eastern flank (+1), Suwalki Gap — land corridor between Belarus and Kaliningrad, highest-density NATO chokepoint on land (+1)",
        "key_structural_interests": ["NATO flank", "Suwalki Gap"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "LU", "name": "Luxembourg",
        "structural_interest_score": 0,
        "score_rationale": "No structural indicators",
        "key_structural_interests": [],
        "suppression_baseline": "low_coverage",
    },
    # --- M ---
    {
        "iso": "MG", "name": "Madagascar",
        "structural_interest_score": 2,
        "score_rationale": "Strategic mineral deposits — nickel, cobalt, rare earths (+2)",
        "key_structural_interests": ["strategic minerals", "cobalt"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "MW", "name": "Malawi",
        "structural_interest_score": 0,
        "score_rationale": "No structural indicators",
        "key_structural_interests": [],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "MY", "name": "Malaysia",
        "structural_interest_score": 5,
        "score_rationale": "Co-controls Malacca Strait — world's busiest maritime chokepoint (+3), major hydrocarbon producer (+2)",
        "key_structural_interests": ["maritime chokepoint", "Malacca Strait", "hydrocarbons"],
        "suppression_baseline": "moderate_coverage",
    },
    {
        "iso": "MV", "name": "Maldives",
        "structural_interest_score": 2,
        "score_rationale": "Strategic Indian Ocean position — sits astride major shipping lanes (+1), China-India competition for basing access (+1)",
        "key_structural_interests": ["Indian Ocean", "BRI exposure"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "ML", "name": "Mali",
        "structural_interest_score": 5,
        "score_rationale": "Active Sahel jihadist conflict (+2), gold and strategic mineral deposits (+2), Russia/Wagner proxy hub — French expulsion (+1)",
        "key_structural_interests": ["active conflict", "strategic minerals", "gold", "proxy hub", "Wagner"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "MT", "name": "Malta",
        "structural_interest_score": 1,
        "score_rationale": "Central Mediterranean position — sits at Sicily Channel, narrowest point of Med (+1)",
        "key_structural_interests": ["Mediterranean corridor"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "MH", "name": "Marshall Islands",
        "structural_interest_score": 1,
        "score_rationale": "US Kwajalein Atoll missile test range and basing (+1)",
        "key_structural_interests": ["US basing"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "MR", "name": "Mauritania",
        "structural_interest_score": 2,
        "score_rationale": "Sahel jihadist spillover — active pressure on northern border (+1), emerging hydrocarbon production (+1)",
        "key_structural_interests": ["Sahel spillover", "hydrocarbons"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "MU", "name": "Mauritius",
        "structural_interest_score": 1,
        "score_rationale": "Indian Ocean strategic position — Diego Garcia adjacent, EEZ contest with UK (+1)",
        "key_structural_interests": ["Indian Ocean"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "MX", "name": "Mexico",
        "structural_interest_score": 4,
        "score_rationale": "Western Hemisphere presence (+1), major hydrocarbon producer (+2), regional power (+1)",
        "key_structural_interests": ["hydrocarbons", "regional power", "Western Hemisphere"],
        "suppression_baseline": "high_coverage",
    },
    {
        "iso": "FM", "name": "Micronesia",
        "structural_interest_score": 1,
        "score_rationale": "Pacific strategic contest — US Compact of Free Association (+1)",
        "key_structural_interests": ["US basing"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "MD", "name": "Moldova",
        "structural_interest_score": 3,
        "score_rationale": "Occupied territory — Transnistria under Russian control, Russian troops present (+2), active proxy contest Russia-EU (+1)",
        "key_structural_interests": ["occupied territory", "proxy hub"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "MC", "name": "Monaco",
        "structural_interest_score": 0,
        "score_rationale": "No structural indicators",
        "key_structural_interests": [],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "MN", "name": "Mongolia",
        "structural_interest_score": 3,
        "score_rationale": "Major strategic mineral deposits — copper, coal, rare earths (+2), BRI/Chinese economic dependency (+1)",
        "key_structural_interests": ["strategic minerals", "BRI exposure"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "ME", "name": "Montenegro",
        "structural_interest_score": 1,
        "score_rationale": "NATO Adriatic flank (+1)",
        "key_structural_interests": ["NATO flank"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "MA", "name": "Morocco",
        "structural_interest_score": 4,
        "score_rationale": "World's largest phosphate reserves — critical for global food security (+2), controls Gibraltar Strait approach from south (+1), regional power in Maghreb/Sahel (+1)",
        "key_structural_interests": ["strategic minerals", "phosphates", "maritime corridor", "regional power"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "MZ", "name": "Mozambique",
        "structural_interest_score": 4,
        "score_rationale": "Active ISIS-affiliate conflict in Cabo Delgado (+2), massive LNG reserves — Rovuma basin (+2)",
        "key_structural_interests": ["active conflict", "hydrocarbons", "LNG"],
        "suppression_baseline": "suppressed",
    },
    {
        "iso": "MM", "name": "Myanmar",
        "structural_interest_score": 5,
        "score_rationale": "Active civil war — post-coup resistance vs. military (+2), rare earth and jade deposits — Chinese mining dominance (+2), BRI/Kyaukphyu port — Chinese Indian Ocean access (+1)",
        "key_structural_interests": ["active conflict", "strategic minerals", "BRI exposure", "Chinese access"],
        "suppression_baseline": "moderate_coverage",
    },
    # --- N ---
    {
        "iso": "NA", "name": "Namibia",
        "structural_interest_score": 4,
        "score_rationale": "Major uranium deposits (+2), significant offshore hydrocarbon discoveries — Orange Basin (+2)",
        "key_structural_interests": ["strategic minerals", "uranium", "hydrocarbons"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "NR", "name": "Nauru",
        "structural_interest_score": 0,
        "score_rationale": "No structural indicators",
        "key_structural_interests": [],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "NP", "name": "Nepal",
        "structural_interest_score": 2,
        "score_rationale": "China-India competition for influence — Himalayan buffer state (+1), BRI/Chinese infrastructure pressure (+1)",
        "key_structural_interests": ["China-India contest", "BRI exposure"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "NL", "name": "Netherlands",
        "structural_interest_score": 2,
        "score_rationale": "US tactical nuclear weapons hosted at Volkel Air Base (+2)",
        "key_structural_interests": ["nuclear hosting"],
        "suppression_baseline": "moderate_coverage",
    },
    {
        "iso": "NZ", "name": "New Zealand",
        "structural_interest_score": 2,
        "score_rationale": "Five Eyes partner, US intelligence integration (+1), strategic minerals potential (+1)",
        "key_structural_interests": ["US partner", "strategic minerals"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "NI", "name": "Nicaragua",
        "structural_interest_score": 2,
        "score_rationale": "Western Hemisphere presence (+1), active US sanctions regime (+1)",
        "key_structural_interests": ["Western Hemisphere", "sanctions"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "NE", "name": "Niger",
        "structural_interest_score": 5,
        "score_rationale": "Active Sahel conflict — post-coup jihadist expansion (+2), major uranium producer — supplied French nuclear program (+2), Sahel proxy contest — French expulsion, Russian/Wagner presence (+1)",
        "key_structural_interests": ["active conflict", "strategic minerals", "uranium", "proxy hub"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "NG", "name": "Nigeria",
        "structural_interest_score": 5,
        "score_rationale": "Largest African hydrocarbon producer (+2), active Boko Haram, IPOB, and Niger Delta conflicts (+2), regional power in West Africa (+1)",
        "key_structural_interests": ["hydrocarbons", "active conflict", "regional power"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "KP", "name": "North Korea",
        "structural_interest_score": 5,
        "score_rationale": "Active nuclear weapons and ICBM program (+2), comprehensive sanctions regime (+1), Russia-China proxy buffer — troops deployed to Ukraine (+1), active conflict participation (+1)",
        "key_structural_interests": ["nuclear program", "sanctions", "proxy hub", "active conflict"],
        "suppression_baseline": "high_coverage",
    },
    {
        "iso": "MK", "name": "North Macedonia",
        "structural_interest_score": 0,
        "score_rationale": "No structural indicators; NATO/EU accession member",
        "key_structural_interests": [],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "NO", "name": "Norway",
        "structural_interest_score": 5,
        "score_rationale": "Major hydrocarbon producer — European gas anchor (+2), rare earth deposits including world-class Fen discovery (+2), Arctic strategic position (+1)",
        "key_structural_interests": ["hydrocarbons", "strategic minerals", "rare earths", "Arctic"],
        "suppression_baseline": "moderate_coverage",
    },
    # --- O ---
    {
        "iso": "OM", "name": "Oman",
        "structural_interest_score": 6,
        "score_rationale": "Controls southern shore of Strait of Hormuz — critical oil chokepoint (+3), significant hydrocarbon reserves (+2), US basing access agreements (+1)",
        "key_structural_interests": ["maritime chokepoint", "Strait of Hormuz", "hydrocarbons", "US basing"],
        "suppression_baseline": "low_coverage",
    },
    # --- P ---
    {
        "iso": "PK", "name": "Pakistan",
        "structural_interest_score": 6,
        "score_rationale": "Active nuclear weapons program (+2), active conflict — TTP insurgency, Baloch separatism (+2), major BRI/CPEC corridor (+1), regional proxy hub — Taliban, Afghan spillover (+1)",
        "key_structural_interests": ["nuclear program", "active conflict", "BRI exposure", "proxy hub"],
        "suppression_baseline": "high_coverage",
    },
    {
        "iso": "PW", "name": "Palau",
        "structural_interest_score": 1,
        "score_rationale": "US Compact of Free Association — Pacific strategic positioning (+1)",
        "key_structural_interests": ["US basing"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "PS", "name": "Palestine",
        "structural_interest_score": 3,
        "score_rationale": "Active conflict — Gaza war (+2), Iran/Hezbollah proxy theater (+1)",
        "key_structural_interests": ["active conflict", "proxy hub"],
        "suppression_baseline": "high_coverage",
    },
    {
        "iso": "PA", "name": "Panama",
        "structural_interest_score": 5,
        "score_rationale": "Panama Canal — Western Hemisphere chokepoint connecting Atlantic and Pacific (+3), Western Hemisphere presence (+1), Chinese BRI/port operator influence (+1)",
        "key_structural_interests": ["maritime chokepoint", "Panama Canal", "Western Hemisphere", "BRI exposure"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "PG", "name": "Papua New Guinea",
        "structural_interest_score": 3,
        "score_rationale": "Strategic mineral deposits — gold, copper, LNG (+2), Pacific strategic contest — US/Australia vs. China (+1)",
        "key_structural_interests": ["strategic minerals", "hydrocarbons"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "PY", "name": "Paraguay",
        "structural_interest_score": 1,
        "score_rationale": "Western Hemisphere presence (+1)",
        "key_structural_interests": ["Western Hemisphere"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "PE", "name": "Peru",
        "structural_interest_score": 3,
        "score_rationale": "Western Hemisphere presence (+1), major strategic minerals — copper, lithium, silver (+2)",
        "key_structural_interests": ["strategic minerals", "copper", "lithium", "Western Hemisphere"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "PH", "name": "Philippines",
        "structural_interest_score": 5,
        "score_rationale": "South China Sea — controls key straits including San Bernardino and Luzon (+3), major US basing resurgence — EDCA sites (+1), active low-level conflict — NPA, Abu Sayyaf (+1)",
        "key_structural_interests": ["maritime chokepoint", "South China Sea", "US basing", "active conflict"],
        "suppression_baseline": "moderate_coverage",
    },
    {
        "iso": "PL", "name": "Poland",
        "structural_interest_score": 3,
        "score_rationale": "NATO eastern flank — largest non-US NATO army (+1), major US basing expansion (+1), Suwalki Gap border state (+1)",
        "key_structural_interests": ["NATO flank", "US basing", "Suwalki Gap"],
        "suppression_baseline": "moderate_coverage",
    },
    {
        "iso": "PT", "name": "Portugal",
        "structural_interest_score": 2,
        "score_rationale": "Azores — strategic North Atlantic position, US Lajes Air Base (+1), lithium deposits — significant European reserves (+1)",
        "key_structural_interests": ["US basing", "strategic minerals"],
        "suppression_baseline": "low_coverage",
    },
    # --- Q ---
    {
        "iso": "QA", "name": "Qatar",
        "structural_interest_score": 4,
        "score_rationale": "World's largest LNG exporter — hydrocarbon reserves (+2), Al Udeid Air Base — largest US air base in Middle East (+1), proxy hub — Hamas, Taliban mediation (+1)",
        "key_structural_interests": ["hydrocarbons", "LNG", "US basing", "proxy hub"],
        "suppression_baseline": "moderate_coverage",
    },
    # --- R ---
    {
        "iso": "RO", "name": "Romania",
        "structural_interest_score": 2,
        "score_rationale": "NATO Black Sea flank (+1), US Deveselu missile defense and basing (+1)",
        "key_structural_interests": ["NATO flank", "US basing"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "RU", "name": "Russia",
        "structural_interest_score": 10,
        "score_rationale": "Active nuclear weapons — largest arsenal (+2), major hydrocarbon producer and pipeline network (+2), active conflict — Ukraine war (+2), comprehensive sanctions regime (+1), regional power and global proxy hub (+1), controls Arctic sea routes (+1), strategic minerals (+1)",
        "key_structural_interests": ["nuclear program", "hydrocarbons", "active conflict", "sanctions", "regional power", "Arctic", "proxy hub"],
        "suppression_baseline": "high_coverage",
    },
    {
        "iso": "RW", "name": "Rwanda",
        "structural_interest_score": 3,
        "score_rationale": "Active conflict — DRC/M23 proxy war, direct military involvement (+2), regional proxy hub in Great Lakes (+1)",
        "key_structural_interests": ["active conflict", "proxy hub"],
        "suppression_baseline": "low_coverage",
    },
    # --- S ---
    {
        "iso": "KN", "name": "Saint Kitts and Nevis",
        "structural_interest_score": 1,
        "score_rationale": "Western Hemisphere presence (+1)",
        "key_structural_interests": ["Western Hemisphere"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "LC", "name": "Saint Lucia",
        "structural_interest_score": 1,
        "score_rationale": "Western Hemisphere presence (+1)",
        "key_structural_interests": ["Western Hemisphere"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "VC", "name": "Saint Vincent and the Grenadines",
        "structural_interest_score": 1,
        "score_rationale": "Western Hemisphere presence (+1)",
        "key_structural_interests": ["Western Hemisphere"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "WS", "name": "Samoa",
        "structural_interest_score": 1,
        "score_rationale": "Pacific strategic contest — Chinese BRI infrastructure investment (+1)",
        "key_structural_interests": ["BRI exposure"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "SM", "name": "San Marino",
        "structural_interest_score": 0,
        "score_rationale": "No structural indicators",
        "key_structural_interests": [],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "ST", "name": "São Tomé and Príncipe",
        "structural_interest_score": 1,
        "score_rationale": "Gulf of Guinea offshore hydrocarbon potential (+1)",
        "key_structural_interests": ["hydrocarbons"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "SA", "name": "Saudi Arabia",
        "structural_interest_score": 6,
        "score_rationale": "World's largest conventional hydrocarbon reserves (+2), major US basing and security partnership (+1), regional power (+1), proxy hub — Yemen war, Lebanon, Palestinian funding (+1), active sanctions on adversaries (+1)",
        "key_structural_interests": ["hydrocarbons", "US basing", "regional power", "proxy hub"],
        "suppression_baseline": "moderate_coverage",
    },
    {
        "iso": "SN", "name": "Senegal",
        "structural_interest_score": 2,
        "score_rationale": "Major new offshore LNG discoveries — becoming significant producer (+2)",
        "key_structural_interests": ["hydrocarbons", "LNG"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "RS", "name": "Serbia",
        "structural_interest_score": 2,
        "score_rationale": "Russia-EU proxy contest — refuses sanctions, Serbian-Kosovo tension (+1), Chinese BRI investment hub in Balkans (+1)",
        "key_structural_interests": ["proxy hub", "BRI exposure"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "SC", "name": "Seychelles",
        "structural_interest_score": 1,
        "score_rationale": "Indian Ocean strategic position — key EEZ in central Indian Ocean (+1)",
        "key_structural_interests": ["Indian Ocean"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "SL", "name": "Sierra Leone",
        "structural_interest_score": 1,
        "score_rationale": "Rutile and strategic mineral deposits (+1)",
        "key_structural_interests": ["strategic minerals"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "SG", "name": "Singapore",
        "structural_interest_score": 5,
        "score_rationale": "Controls eastern Malacca Strait — most critical maritime chokepoint by volume (+3), major US naval access (+1), regional financial and logistics hub (+1)",
        "key_structural_interests": ["maritime chokepoint", "Malacca Strait", "US basing", "regional hub"],
        "suppression_baseline": "moderate_coverage",
    },
    {
        "iso": "SK", "name": "Slovakia",
        "structural_interest_score": 0,
        "score_rationale": "No structural indicators; NATO/EU member",
        "key_structural_interests": [],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "SI", "name": "Slovenia",
        "structural_interest_score": 0,
        "score_rationale": "No structural indicators; NATO/EU member",
        "key_structural_interests": [],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "SB", "name": "Solomon Islands",
        "structural_interest_score": 1,
        "score_rationale": "Chinese security pact — Pacific basing contest, potential PLA access (+1)",
        "key_structural_interests": ["BRI exposure"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "SO", "name": "Somalia",
        "structural_interest_score": 4,
        "score_rationale": "Active conflict — al-Shabaab insurgency, state fragility (+2), Bab-el-Mandeb adjacent — Indian Ocean piracy corridor (+1), proxy hub for regional powers (+1)",
        "key_structural_interests": ["active conflict", "maritime corridor", "proxy hub"],
        "suppression_baseline": "suppressed",
    },
    {
        "iso": "ZA", "name": "South Africa",
        "structural_interest_score": 4,
        "score_rationale": "World-class strategic minerals — platinum group metals, chrome, manganese (+2), regional power in sub-Saharan Africa (+1), Cape of Good Hope sea route — alternative to Suez (+1)",
        "key_structural_interests": ["strategic minerals", "regional power", "maritime corridor"],
        "suppression_baseline": "moderate_coverage",
    },
    {
        "iso": "KR", "name": "South Korea",
        "structural_interest_score": 4,
        "score_rationale": "Major US basing — 28,000 troops, USFK (+1), latent nuclear capability — active discussion of indigenous program (+2), regional power and semiconductor/industrial hub (+1)",
        "key_structural_interests": ["US basing", "nuclear program", "regional power"],
        "suppression_baseline": "high_coverage",
    },
    {
        "iso": "SS", "name": "South Sudan",
        "structural_interest_score": 4,
        "score_rationale": "Active civil conflict — recurrent war, mass atrocities (+2), major hydrocarbon reserves — landlocked oil producer (+2)",
        "key_structural_interests": ["active conflict", "hydrocarbons"],
        "suppression_baseline": "suppressed",
    },
    {
        "iso": "ES", "name": "Spain",
        "structural_interest_score": 2,
        "score_rationale": "Major US basing — Rota naval base, Morón Air Base (+1), Gibraltar Strait — controls northern approach (+1)",
        "key_structural_interests": ["US basing", "maritime corridor"],
        "suppression_baseline": "moderate_coverage",
    },
    {
        "iso": "LK", "name": "Sri Lanka",
        "structural_interest_score": 2,
        "score_rationale": "Chinese BRI debt trap — Hambantota Port 99-year lease (+1), Indian Ocean strategic position astride major shipping lanes (+1)",
        "key_structural_interests": ["BRI exposure", "Indian Ocean"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "SD", "name": "Sudan",
        "structural_interest_score": 5,
        "score_rationale": "Active civil war — SAF vs. RSF, mass atrocities (+2), hydrocarbon production (+1), Red Sea access — Russian naval base negotiations (+1), proxy hub UAE/Egypt/Russia/Turkey contest (+1)",
        "key_structural_interests": ["active conflict", "hydrocarbons", "Red Sea", "proxy hub"],
        "suppression_baseline": "suppressed",
    },
    {
        "iso": "SR", "name": "Suriname",
        "structural_interest_score": 3,
        "score_rationale": "Western Hemisphere presence (+1), major new deepwater hydrocarbon discoveries — Stabroek basin extension (+2)",
        "key_structural_interests": ["hydrocarbons", "Western Hemisphere"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "SE", "name": "Sweden",
        "structural_interest_score": 2,
        "score_rationale": "NATO new member with Baltic Sea strategic position (+1), rare earth deposits — Kiruna LKAB discovery, largest in Europe (+1)",
        "key_structural_interests": ["NATO flank", "strategic minerals"],
        "suppression_baseline": "moderate_coverage",
    },
    {
        "iso": "CH", "name": "Switzerland",
        "structural_interest_score": 0,
        "score_rationale": "No structural indicators; neutral financial center",
        "key_structural_interests": [],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "SY", "name": "Syria",
        "structural_interest_score": 6,
        "score_rationale": "Active conflict — post-Assad fragmentation, ongoing fighting (+2), occupied territory — Israeli-held Golan, Turkish zones, US/SDF zone (+2), active sanctions regime (+1), proxy hub Russia/Iran/Turkey/US/Israel (+1)",
        "key_structural_interests": ["active conflict", "occupied territory", "sanctions", "proxy hub"],
        "suppression_baseline": "moderate_coverage",
    },
    # --- T ---
    {
        "iso": "TW", "name": "Taiwan",
        "structural_interest_score": 7,
        "score_rationale": "Active military threat — PLA encirclement exercises, imminent invasion scenario (+2), controls >90% of advanced semiconductor manufacturing — strategic chokepoint (+2), US security commitment, major arms sales (+1), regional power in global tech supply chain (+1), active PRC sanctions and blockade pressure (+1)",
        "key_structural_interests": ["active conflict", "strategic minerals", "semiconductors", "US partner", "sanctions"],
        "suppression_baseline": "high_coverage",
    },
    {
        "iso": "TJ", "name": "Tajikistan",
        "structural_interest_score": 2,
        "score_rationale": "Afghan border — narco-trafficking and insurgent spillover corridor (+1), BRI/Chinese infrastructure exposure (+1)",
        "key_structural_interests": ["BRI exposure", "Afghan corridor"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "TZ", "name": "Tanzania",
        "structural_interest_score": 3,
        "score_rationale": "Strategic minerals — gold, tanzanite, niobium, rare earth potential (+2), LNG reserves — Rovuma basin shared with Mozambique (+1)",
        "key_structural_interests": ["strategic minerals", "hydrocarbons"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "TH", "name": "Thailand",
        "structural_interest_score": 3,
        "score_rationale": "Kra Isthmus — proposed canal would bypass Malacca, strategic geography (+1), US basing access and treaty ally (+1), regional hub for Southeast Asia (+1)",
        "key_structural_interests": ["maritime corridor", "US basing", "regional hub"],
        "suppression_baseline": "moderate_coverage",
    },
    {
        "iso": "TL", "name": "Timor-Leste",
        "structural_interest_score": 2,
        "score_rationale": "Timor Sea hydrocarbon reserves — Greater Sunrise field (+2)",
        "key_structural_interests": ["hydrocarbons"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "TG", "name": "Togo",
        "structural_interest_score": 0,
        "score_rationale": "No structural indicators",
        "key_structural_interests": [],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "TO", "name": "Tonga",
        "structural_interest_score": 1,
        "score_rationale": "Pacific strategic contest — Chinese BRI infrastructure (+1)",
        "key_structural_interests": ["BRI exposure"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "TT", "name": "Trinidad and Tobago",
        "structural_interest_score": 3,
        "score_rationale": "Western Hemisphere presence (+1), significant hydrocarbon production — LNG exporter (+2)",
        "key_structural_interests": ["hydrocarbons", "Western Hemisphere"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "TN", "name": "Tunisia",
        "structural_interest_score": 2,
        "score_rationale": "Sicily Channel — sits at Mediterranean narrowing (+1), Sahel/Libya instability spillover and migration corridor (+1)",
        "key_structural_interests": ["maritime corridor", "Sahel spillover"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "TR", "name": "Turkey",
        "structural_interest_score": 8,
        "score_rationale": "Controls Turkish Straits — Bosphorus and Dardanelles, only Black Sea exit (+3), US nuclear weapons at Incirlik (+2), major US basing (+1), regional power — NATO member playing both sides (+1), proxy hub Syria/Libya/Azerbaijan/Ukraine (+1)",
        "key_structural_interests": ["maritime chokepoint", "Turkish Straits", "Bosphorus", "nuclear hosting", "US basing", "regional power", "proxy hub"],
        "suppression_baseline": "high_coverage",
    },
    {
        "iso": "TM", "name": "Turkmenistan",
        "structural_interest_score": 2,
        "score_rationale": "World's fourth-largest natural gas reserves (+2)",
        "key_structural_interests": ["hydrocarbons"],
        "suppression_baseline": "suppressed",
    },
    {
        "iso": "TV", "name": "Tuvalu",
        "structural_interest_score": 0,
        "score_rationale": "No structural indicators",
        "key_structural_interests": [],
        "suppression_baseline": "low_coverage",
    },
    # --- U ---
    {
        "iso": "UG", "name": "Uganda",
        "structural_interest_score": 4,
        "score_rationale": "Active conflict — ADF insurgency, Great Lakes instability (+2), Lake Albert hydrocarbon reserves — major oil development underway (+2)",
        "key_structural_interests": ["active conflict", "hydrocarbons"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "UA", "name": "Ukraine",
        "structural_interest_score": 8,
        "score_rationale": "Active full-scale war with Russia (+2), occupied territory — Crimea, Donbas (+2), major strategic minerals — rare earths, titanium, manganese, lithium (+2), active broad sanctions regime (+1), NATO/EU proxy contest (+1)",
        "key_structural_interests": ["active conflict", "occupied territory", "strategic minerals", "sanctions", "proxy hub"],
        "suppression_baseline": "high_coverage",
    },
    {
        "iso": "AE", "name": "United Arab Emirates",
        "structural_interest_score": 4,
        "score_rationale": "Major hydrocarbon reserves (+2), US basing access — Al Dhafra Air Base (+1), regional proxy hub — Sudan, Libya, Horn of Africa (+1)",
        "key_structural_interests": ["hydrocarbons", "US basing", "proxy hub"],
        "suppression_baseline": "moderate_coverage",
    },
    {
        "iso": "GB", "name": "United Kingdom",
        "structural_interest_score": 5,
        "score_rationale": "Active nuclear weapons program — Trident (+2), regional power and global basing network (+1), major US interoperability partner — Five Eyes, AUKUS (+1), controls Gibraltar and Diego Garcia chokepoints (+1)",
        "key_structural_interests": ["nuclear program", "regional power", "US partner", "maritime chokepoint"],
        "suppression_baseline": "high_coverage",
    },
    {
        "iso": "US", "name": "United States",
        "structural_interest_score": 10,
        "score_rationale": "World's largest nuclear arsenal (+2), global military basing network — 750+ installations (+1), major hydrocarbon producer (+2), strategic minerals processing (+2), Western Hemisphere hegemon (+1), global proxy hub and sanctions issuer (+1), regional power in all theaters (+1)",
        "key_structural_interests": ["nuclear program", "US basing", "hydrocarbons", "strategic minerals", "Western Hemisphere", "regional power"],
        "suppression_baseline": "high_coverage",
    },
    {
        "iso": "UY", "name": "Uruguay",
        "structural_interest_score": 1,
        "score_rationale": "Western Hemisphere presence (+1)",
        "key_structural_interests": ["Western Hemisphere"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "UZ", "name": "Uzbekistan",
        "structural_interest_score": 3,
        "score_rationale": "Strategic minerals — uranium, gold, copper (+2), BRI/Chinese infrastructure exposure (+1)",
        "key_structural_interests": ["strategic minerals", "uranium", "BRI exposure"],
        "suppression_baseline": "low_coverage",
    },
    # --- V ---
    {
        "iso": "VU", "name": "Vanuatu",
        "structural_interest_score": 1,
        "score_rationale": "Chinese BRI/port investment — Pacific basing contest (+1)",
        "key_structural_interests": ["BRI exposure"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "VE", "name": "Venezuela",
        "structural_interest_score": 4,
        "score_rationale": "Western Hemisphere presence (+1), world's largest proven hydrocarbon reserves (+2), comprehensive US sanctions regime (+1)",
        "key_structural_interests": ["hydrocarbons", "Western Hemisphere", "sanctions"],
        "suppression_baseline": "moderate_coverage",
    },
    {
        "iso": "VN", "name": "Vietnam",
        "structural_interest_score": 4,
        "score_rationale": "South China Sea territorial disputes — Paracel and Spratly Islands (+1), world's second-largest rare earth reserves (+2), US defense relationship expanding post-normalization (+1)",
        "key_structural_interests": ["South China Sea", "strategic minerals", "rare earths", "US partner"],
        "suppression_baseline": "moderate_coverage",
    },
    # --- Y ---
    {
        "iso": "YE", "name": "Yemen",
        "structural_interest_score": 7,
        "score_rationale": "Houthi control of Bab-el-Mandeb approaches — Red Sea chokepoint (+3), active full-scale conflict (+2), Iran-Saudi proxy theater (+1), active sanctions on Houthis (+1)",
        "key_structural_interests": ["maritime chokepoint", "Bab-el-Mandeb", "active conflict", "proxy hub", "sanctions"],
        "suppression_baseline": "moderate_coverage",
    },
    # --- Z ---
    {
        "iso": "ZM", "name": "Zambia",
        "structural_interest_score": 3,
        "score_rationale": "Major copper and cobalt reserves — Copperbelt (+2), Chinese BRI/debt exposure — significant loan distress (+1)",
        "key_structural_interests": ["strategic minerals", "copper", "cobalt", "BRI exposure"],
        "suppression_baseline": "low_coverage",
    },
    {
        "iso": "ZW", "name": "Zimbabwe",
        "structural_interest_score": 3,
        "score_rationale": "Strategic minerals — platinum group metals, chrome, lithium (+2), active sanctions regime (+1)",
        "key_structural_interests": ["strategic minerals", "platinum", "lithium", "sanctions"],
        "suppression_baseline": "low_coverage",
    },
]
